[build]
  functions = "netlify/functions"

# (Опционально) CORS для функции
[[headers]]
  for = "/.netlify/functions/notify"
  [headers.values]
    Access-Control-Allow-Origin = "https://evliseoutlet.netlify.app"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Preflight
[[redirects]]
  from = "/.netlify/functions/notify"
  to = "/.netlify/functions/notify"
  status = 200
