[build]
  functions = "netlify/functions"

# CORS для notify
[[headers]]
  for = "/.netlify/functions/notify"
  [headers.values]
    Access-Control-Allow-Origin = "https://evliseoutlet.netlify.app"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# CORS для orders (если фронт стучится к ней напрямую)
[[headers]]
  for = "/.netlify/functions/orders"
  [headers.values]
    Access-Control-Allow-Origin = "https://evliseoutlet.netlify.app"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
